### ISSUE TITLE
Case sensitive forms

### ISSUE THREAD

**Issue by crystaltype** [googlefonts/zen-tokyo-zoo#2]
Hello,

I have some questions when making the case-sensitive forms for this font.

The uppercase glyphs all have 3 strokes like this:

<img width="106" alt="Screen Shot 2021-03-17 at 22 22 10" src="https://user-images.githubusercontent.com/20129845/111493991-aa689680-8770-11eb-8811-8e88d1f82389.png">

When making case sensitive ones for the lowercase glyphs, I would reduce them to 2 strokes.
<img width="134" alt="Screen Shot 2021-03-17 at 22 23 04" src="https://user-images.githubusercontent.com/20129845/111494075-beac9380-8770-11eb-88de-e0867ad14d8b.png">

But for the glyphs that already have 2 strokes, should I reduce them to only 1?
<img width="366" alt="Screen Shot 2021-03-17 at 22 34 06" src="https://user-images.githubusercontent.com/20129845/111494270-e8fe5100-8770-11eb-8364-2a1ab09b47a3.png">

to
<img width="238" alt="Screen Shot 2021-03-17 at 22 35 29" src="https://user-images.githubusercontent.com/20129845/111494706-47c3ca80-8771-11eb-8dfc-b474e58b5edb.png">

or
<img width="148" alt="Screen Shot 2021-03-17 at 22 36 47" src="https://user-images.githubusercontent.com/20129845/111494927-7641a580-8771-11eb-990a-9ff53f4ac423.png">

If I keep it as 2 strokes, I would have trouble with glyphs like two superior or three superior, as it's not enough space to keep the stroke weight and spacing between those strokes intact.
Any help could be appreciated!

**Comment by vv-monsalve** [comment]
Pasting here the complete list of the glyphs needed
![image](https://user-images.githubusercontent.com/48698976/111495948-d7379200-870d-11eb-8475-2f24b4240c18.png)


I think there could be two options:
a). Keeping at least two strokes but with a different but visually proportional stroke value to preserve the spirit of the font. Quick try:

![Screen Shot 2021-03-17 at 10 47 35](https://user-images.githubusercontent.com/48698976/111496306-34cbde80-870e-11eb-9f70-414b3e479921.png)

b). Reducing them to one, but I wonder how would it work among the entire system, as the single stroke has been used only for some diacritic marks and these would be glyphs that would interact with the other letters in the same text line.

**Comment by crystaltype** [comment]
@vv-monsalve 
Thank you! I ended up using your a) suggestion.

I drawed all the glyphs and named all the case ones with .case. Then I used the auto-generate function of glyphsapp to generate the feature. But when I tried to type the case ones + a symbol, it doesn't substitute the .case counterpart. Do you know what I'm missing here?
![Uploading Screen Shot 2021-03-20 at 20.59.20.png…]()

**Comment by crystaltype** [comment]
Here are the complete case-sensitive glyphs I drew.

<img width="991" alt="Screen Shot 2021-03-20 at 21 01 12" src="https://user-images.githubusercontent.com/20129845/111871985-7a630280-89bf-11eb-9512-dbb81358ff47.png">

**Comment by vv-monsalve** [comment]
Hi @crystaltype,
I've pulled the files, produced new fonts and tried them in InDesign, there the `caps` feature is working fine. Bear in mind that for it to work you need to apply the "All Caps" option in the Character menu. You wouldn't get the behaviour by "changing case" to UPPERCASE in the Type menu.

I've pushed new font files and some proof material in the documentation. Please remember there is the Action in the repository that creates a new font every time a [new push](https://github.com/googlefonts/zen-tokyo-zoo/actions/runs/681705384) is done, so you can download it and make some trials and proofs to check the font is working.

There are some issues to fix though:

- [ ] `exclamdown` position
- [ ] `copyright`, `registered`, `TM` and other symbols legibility in lowercase forms. Perhaps the letters could have only one stroke.
- [ ] `ampersand` legibility
- [ ] thickness of horizontal strokes in lowercase numbers
- [ ] `bullet` legibility
- [ ] lowercase ellipsis legibility (it seems more space among dots is needed)
- [ ] kerning between `space` and some letters like `y`
- [ ] math forms should be horizontally aligned
- [ ] `equal` legibility or differentiation with `minus`
- [ ] lowercase `three-quarters` is missing
- [ ] `questiondown` is the only symbol that is not working in 'All Caps'
- [ ] spacing between punctuation and letters, e.g. `quoteright.case`

![Screen Shot 2021-03-23 at 21 31 45](https://user-images.githubusercontent.com/48698976/112249198-57398c80-8c25-11eb-9c62-0298723f6b9d.png)
![Screen Shot 2021-03-23 at 21 38 25](https://user-images.githubusercontent.com/48698976/112249202-586ab980-8c25-11eb-9769-b2613b48f195.png)

**Comment by vv-monsalve** [comment]
@m4rc1e this would be the third Latin project from Zen Fonts, in case you would like to check it before we make the PR to GF. You can see a [pdf here](https://github.com/googlefonts/zen-tokyo-zoo/blob/QA/documentation/Proof-Zen-Tpkyo-Zoo.pdf).

**Comment by crystaltype** [comment]
@vv-monsalve thank you!

I've fixed most of the issues, but I'm not sure about how to fix `ampersand` legibility. Should I reduce it to 1 stroke too? And nd I'm also not entirely sure about what you mean by `equal legibility or differentiation with minus` either. Could you please tell me in more detail?

**Comment by vv-monsalve** [comment]
New Images after fixes:

![Proof-Zen-Tpkyo-Zoo-v1002_Page_2](https://user-images.githubusercontent.com/48698976/116727579-5f19e880-a9aa-11eb-831f-ce53a78bd855.png)
![Proof-Zen-Tpkyo-Zoo-v1002_Page_3](https://user-images.githubusercontent.com/48698976/116727583-5fb27f00-a9aa-11eb-8536-c2cbe0f5fd85.png)

**Comment by davelab6** [comment]
@vv-monsalve what is the status for this? The Zen Fonts for Japanese are becoming ready, so I wonder about this update :)

**Comment by vv-monsalve** [comment]
Hi @davelab6 

- The [PR](https://github.com/google/fonts/pulls?q=is%3Apr+zen+tokyo+zoo+is%3Aclosed) was done on May 5th
- The font is in [Sandbox](https://fonts.sandbox.google.com/specimen/Zen+Tokyo+Zoo?query=Toky#standard-styles) now
- It's listed in the [To Production list](https://github.com/google/fonts/projects/1#card-60193306) in the Traffic Jam
- And it's listed in line 60 of the Social `Media Plan` (Twitter) tab of the `Pipeline Review` spreadsheet. 

All the Zen Latin Fonts have drafted tweets. If you could have an eye on them and modify/approved them, it would be fantastic ;-)

Closing this Issue here.
